from setuptools import setup, find_packages

setup(
    name='typeidea',
    version='${version}',
    description='Blog System base on Django',
    author='shj',
    author_email='1027118385@qq.com',
    url='https://www.the5fire.com',
    license='MIT',
    packages=find_packages('typeidea'),
    package_dir={'': 'typeidea'},
    package_data={'': [  # 方法一：打包数据文件 需要按目录层级匹配
        'themes/*/*/*/**',
    ]},
    # include_package_data = True,  #方法二：配合MANIFEST.in文件
    install_requires=[

        'asgiref==3.5.0',
        'asttokens==2.0.5',
        'autopep8==1.6.0',
        'backcall==0.2.0',
        'backports.zoneinfo==0.2.1',
        'bcrypt==3.2.0',
        'certifi==2021.10.8',
        'cffi==1.15.0',
        'charset-normalizer==2.0.12',
        'coreapi==2.3.3',
        'coreschema==0.0.4',
        'cryptography==36.0.1',
        'decorator==5.1.1',
        'defusedxml==0.6.0',
        'Deprecated==1.2.13',
        'diff-match-patch==20181111',
        'Django==2.0 ',
        'django-autocomplete-light==3.2.10',
        'django-ckeditor==5.4.0',
        'django-crispy-forms==1.7.2',
        'django-debug-toolbar==1.9.1',
        'django-debug-toolbar-line-profiler==0.6.1',
        'django-formtools==2.1',
        'django-import-export==1.2.0',
        'django-js-asset==2.0.0',
        'django-redis==4.8.0',
        'django-reversion==3.0.4',
        'django-silk==3.0.0',
        'djangorestframework==3.8.2',
        'djdt-flamegraph==0.2.12',
        'et-xmlfile==1.1.0',
        'executing==0.8.3',
        'Fabric3==1.14.post1',
        'future==0.18.2',
        'gprof2dot==2016.10.13',
        'gunicorn==19.7.1',
        'hiredis==0.2.0',
        'httplib2==0.9.2',
        'idna==3.3',
        'itypes==1.2.0',
        'jedi==0.18.1',
        'Jinja2==3.0.3',
        'line-profiler==3.4.0',
        'MarkupPy==1.14',
        'MarkupSafe==2.1.0',
        'matplotlib-inline==0.1.3',
        'meld3==2.0.1',
        'mistune==2.0.2',
        'mysql-client==0.0.1',
        'mysqlclient==1.3.13',
        'odfpy==1.4.1',
        'openpyxl==3.0.9',
        'packaging==21.3',
        'paramiko==2.9.2',
        'parso==0.8.3',
        'passlib==1.7.4',
        'pexpect==4.8.0',
        'pickleshare==0.7.5',
        'Pillow==5.1.0',
        'prompt-toolkit==3.0.28',
        'ptyprocess==0.7.0',
        'pure-eval==0.2.2',
        'pycodestyle==2.8.0',
        'pycparser==2.21',
        'Pygments==2.11.2',
        'Pympler==0.5',
        'PyNaCl==1.5.0',
        'pyparsing==3.0.7',
        'pypiserver==1.4.2',
        'python-dateutil==2.8.2',
        'pytz==2021.3',
        'PyYAML==6.0',
        'redis==4.1.4',
        'requests==2.27.1',
        'six==1.16.0',
        'sqlparse==0.4.2',
        'stack-data==0.2.0',
        'supervisor==4.1.0',
        'tablib==3.2.0',
        'toml==0.10.2',
        'traitlets==5.1.1',
        'uritemplate==4.1.1',
        'urllib3==1.26.8',
        'wcwidth==0.2.5',
        'wrapt==1.13.3',
        'xadmin @ https://github.com/the5fire/django-xadmin/archive/2.0.1.zip',
        'xlrd==2.0.1',
        'xlwt==1.3.0',
        'wheel==0.37.1',

    ],
    extras_require={
        'ipython': ['ipython==6.2.1']
    },
    scripts=[
        'typeidea/manage.py',
    ],
    entry_points={
        'console_scripts': [
            'typeidea_manage=manage:main',
        ]
    },
    classifiers=[  # Optional
        # 软件成熟度如何？一般有一下几种选项
        # 3 - Alpha
        # 4 - Beta
        # 5 - Production/Stable
        'Development Status :: 3 - Alpha',

        # 指明项目的受众
        'Intended Audience :: Developers',
        'Topic :: Software Development :: Libraries',

        # 选择项目的许可证(License)
        'License :: OSI Approved :: MIT License',

        # 指定项目需要使用的Python版本
        'Programming Language :: Python :: 3.8',
    ],
)
